version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PostGresQL@123
      POSTGRES_USER: PortfolioUser
      POSTGRES_DB: PortfolioDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090
